language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
script:
  - asdf plugin-add pulumi https://github.com/canha/asdf-pulumi.git
  - asdf list-all pulumi
  - asdf plugin-test pulumi ./ 'pulumi version'
os:
  - linux
  - osx
